/* GENERATED by tools/trace-notes.py — do not hand-edit.

   One entry per scrap of paper in public/assets/notes/. `rules` is
   every ruled line on the deskewed sheet, in the image's own pixels:
   `y` is the line, `x0`/`x1` are the paper's edges at that line, which
   narrow where the scrap is torn. `deskewed` is the angle that was
   taken out of the photograph and is kept only as a record.

   Read by renderReadings() in js/script.js, which writes a book's
   summary along these lines. A bare global, like the other data
   files. Add a note by dropping a background-free image in that
   folder and running the tool again. */
var notePapers = [
  {"src": "public/assets/notes/note-clipped.webp", "w": 408, "h": 612, "deskewed": 0.0, "rules": [{"y": 155, "x0": 50, "x1": 347}, {"y": 194, "x0": 53, "x1": 343}, {"y": 232, "x0": 52, "x1": 347}, {"y": 271, "x0": 47, "x1": 354}, {"y": 313, "x0": 48, "x1": 352}, {"y": 351, "x0": 49, "x1": 361}, {"y": 390, "x0": 52, "x1": 353}, {"y": 428, "x0": 53, "x1": 348}, {"y": 469, "x0": 51, "x1": 341}, {"y": 508, "x0": 56, "x1": 343}]},
  {"src": "public/assets/notes/note-index-card.webp", "w": 359, "h": 234, "deskewed": -0.0, "rules": [{"y": 35, "x0": 24, "x1": 271}, {"y": 54, "x0": 47, "x1": 310}, {"y": 74, "x0": 24, "x1": 324}, {"y": 93, "x0": 46, "x1": 318}, {"y": 114, "x0": 24, "x1": 333}, {"y": 134, "x0": 46, "x1": 326}, {"y": 154, "x0": 62, "x1": 326}, {"y": 180, "x0": 84, "x1": 326}]},
  {"src": "public/assets/notes/note-taped.webp", "w": 323, "h": 393, "deskewed": -0.0, "rules": [{"y": 91, "x0": 2, "x1": 322}, {"y": 114, "x0": 2, "x1": 322}, {"y": 137, "x0": 3, "x1": 322}, {"y": 160, "x0": 3, "x1": 321}, {"y": 184, "x0": 3, "x1": 321}, {"y": 210, "x0": 3, "x1": 321}, {"y": 232, "x0": 2, "x1": 321}, {"y": 253, "x0": 2, "x1": 321}, {"y": 280, "x0": 3, "x1": 320}, {"y": 304, "x0": 33, "x1": 320}, {"y": 328, "x0": 3, "x1": 320}, {"y": 352, "x0": 29, "x1": 319}, {"y": 376, "x0": 33, "x1": 318}]}
];
