const projectDetails = {
  'artezas': {
    title: 'Arteza',
    subtitle: 'Collaborative digital canvas for sketching, painting, and sharing artwork.',
    motivation: 'I missed the spontaneous creativity of physical sketchbooks when I moved to digital tools. Existing apps felt either too complex or too isolated. Arteza was born from the need for a simple, real‑time collaborative canvas that anyone could jump into.',
    features: [
      'Real‑time collaborative drawing with WebSockets',
      'Brush engine with pressure sensitivity and layers',
      'Public gallery and art sharing with comments',
      'Export to PNG/SVG',
      'User authentication via OAuth'
    ],
    techStack: 'React, Node.js, Socket.io, MongoDB, Canvas API, Docker',
    architecture: 'Frontend (React + Canvas) ↔ WebSocket Server (Socket.io) ↔ MongoDB (persistent storage). User management handled via a separate REST API.',
    codeWalkthrough: [
      'The brush engine is built entirely on HTML5 Canvas; each stroke is serialised as a list of points and broadcast to all connected clients via Socket.io.',
      'The server stores canvas state in MongoDB as a sequence of brush commands, allowing full replay and version history.',
      'See `server/canvasController.js` for the real‑time sync logic, and `client/src/components/Canvas.jsx` for the drawing component.'
    ],
    howToUse: 'Live demo: https://artezas-demo.vercel.app (username: demo, password: demo)',
    results: 'Used by 30+ beta testers during a university workshop; reduced art sharing friction by 70% compared to email‑based workflows.',
    futurePlans: 'Add tablet/mobile support, voice collaboration, and AI‑powered colour suggestions.'
  },
  'anttodo': {
    title: 'AntTodo',
    subtitle: 'Minimalist to‑do list with natural language parsing and smart prioritisation.',
    motivation: 'I kept abandoning to‑do apps because they required too much manual sorting. I wanted something where I could type “Buy groceries tomorrow at 5pm” and have it automatically scheduled and prioritised.',
    features: [
      'Natural language input with date/time extraction',
      'Automatic categorisation using Eisenhower Matrix',
      'Recurring task support',
      'Daily summary view',
      'Dark/light theme'
    ],
    techStack: 'Vue.js, Firebase (Firestore + Auth), NLP.js, Vercel',
    architecture: 'Vue.js SPA → NLP.js library for local parsing → Firestore database. Authentication via Firebase Auth. Hosted on Vercel.',
    codeWalkthrough: [
      'The NLP pipeline uses `compromise` and `chrono` libraries to extract dates, times, and priority cues from the input string.',
      'The Eisenhower Matrix placement is computed from urgency and importance scores derived from keywords and due dates.',
      'Check `src/utils/nlpHelper.js` for the parsing logic.'
    ],
    howToUse: 'https://anttodo.web.app (no login required)',
    results: 'Reduced my personal daily planning time from 10 minutes to under 1 minute. 25 active users in the first month.',
    futurePlans: 'Calendar sync, team sharing, and voice input.'
  },
  'habita': {
    title: 'Habita',
    subtitle: 'Habit tracker with visual streak grid and daily journaling.',
    motivation: 'I needed a habit tracker that felt less like a chore and more like a personal diary. Habita combines streak tracking with short daily reflections to keep motivation high.',
    features: [
      'Habit creation with colour coding',
      'Year‑in‑pixels style streak grid',
      'Daily reflection journal (Markdown)',
      'Reminders via email',
      'Data export (CSV)'
    ],
    techStack: 'Svelte, Supabase, Tailwind CSS, Vite',
    architecture: 'SvelteKit app with Supabase as backend (PostgreSQL, Auth, Storage). Deployed on Netlify.',
    codeWalkthrough: [
      'Each habit is stored in a `habits` table; completions in a `completions` table linked by foreign key.',
      'The streak grid is generated by aggregating completions into an SVG heatmap.',
      'Reflection entries are stored as Markdown and rendered with `marked`.'
    ],
    howToUse: 'https://habita.app (sign up free)',
    results: 'Maintained a 120‑day streak myself; app was featured in a campus productivity newsletter.',
    futurePlans: 'Habit challenges with friends, and integration with fitness trackers.'
  },
  'yosemite-image-translation-gan': {
    title: 'Yosemite GAN',
    subtitle: 'CycleGAN for satellite‑to‑map image translation, trained on Yosemite National Park.',
    motivation: 'I was fascinated by the idea of turning raw satellite imagery into stylised map tiles for outdoor navigation. This project experiments with unpaired image‑to‑image translation using CycleGAN.',
    features: [
      'CycleGAN architecture with ResNet generator',
      'Training on Yosemite satellite ↔ map dataset',
      'Inference script for single image translation',
      'Evaluation metrics (SSIM, FID)'
    ],
    techStack: 'Python, PyTorch, OpenCV, Matplotlib, Jupyter Notebook',
    architecture: 'Training pipeline: Dataset loader → CycleGAN model (two generators, two discriminators) → loss computation (adversarial + cycle consistency) → model checkpointing. Inference: single script loads checkpoint and translates image.',
    codeWalkthrough: [
      'The generator uses 9 ResNet blocks; the discriminator is a PatchGAN.',
      'Cycle‑consistency loss ensures the translated image can be mapped back to the original.',
      'See `train.py` for the training loop and `test_on_image.py` for inference.'
    ],
    howToUse: 'Clone repo, install requirements, download dataset, run `python train.py`. Pretrained model included.',
    results: 'Achieved FID of 52.3 on the test set; visually convincing translations after 200 epochs.',
    futurePlans: 'Extend to other domains (maps ↔ satellite for different regions), and deploy a web demo using ONNX.js.'
  },
  'quantamental-screener': {
    title: 'Quantamental Screener',
    subtitle: 'Stock screener blending fundamental ratios with quantitative technical signals.',
    motivation: 'I wanted to screen stocks not just by P/E or market cap, but also by custom technical indicators (RSI, MACD) to find value entries. Existing platforms were too limited or expensive.',
    features: [
      'Yahoo Finance data scraping',
      'Fundamental filter (P/E, P/B, debt/equity)',
      'Technical indicators (RSI, MACD, moving averages)',
      'Screener results in a sortable table',
      'CSV export'
    ],
    techStack: 'Python, Streamlit, yfinance, pandas, plotly',
    architecture: 'Streamlit web app → yfinance API for data → pandas for processing → plotly for charts. All computation done on‑the‑fly in the browser session.',
    codeWalkthrough: [
      '`screener.py` contains the main logic; indicators are computed using `ta` library.',
      'Custom screen conditions are defined in a JSON config file for flexibility.',
      'Results are displayed in an interactive Streamlit dataframe.'
    ],
    howToUse: 'Live demo: https://quantamental-screener.streamlit.app',
    results: 'Identified 3 undervalued stocks with bullish technicals that later gained 12‑18% within 2 months.',
    futurePlans: 'Add portfolio backtesting, email alerts, and a watchlist feature.'
  },
  'smart_pricing_retention': {
    title: 'Smart Pricing & Retention',
    subtitle: 'Predicts customer churn and recommends optimal pricing tiers for subscription businesses.',
    motivation: 'During an internship, I noticed that small price adjustments could dramatically affect churn. I built this tool to simulate the impact of pricing changes on customer retention.',
    features: [
      'Churn prediction model (XGBoost)',
      'Price elasticity estimation',
      'Revenue impact simulation',
      'Interactive dashboard (Streamlit)',
      'Data preprocessing pipeline'
    ],
    techStack: 'Python, scikit‑learn, XGBoost, Streamlit, pandas, matplotlib',
    architecture: 'Data ingestion (CSV) → feature engineering → model training (churn classifier) → elasticity calculator → Streamlit dashboard for what‑if analysis.',
    codeWalkthrough: [
      'The feature engineering module creates lag‑based usage metrics and pricing history.',
      'The churn model achieves 89% AUC; elasticity is estimated via a simple log‑log regression.',
      'See `model/train.py` and `dashboard/app.py`.'
    ],
    howToUse: 'Run `docker‑compose up` or visit https://pricing‑retention‑demo.onrender.com',
    results: 'Simulated a 15% revenue uplift by recommending a mid‑tier price adjustment for a sample SaaS dataset.',
    futurePlans: 'Integrate real‑time data from Stripe, and add A/B testing simulation.'
  },
  'Wikipedia-Summarizer': {
    title: 'Wikipedia Summarizer',
    subtitle: 'Extractive and abstractive summarisation of Wikipedia articles using BART and TF‑IDF.',
    motivation: 'I often needed quick summaries of long Wikipedia articles for research. I built this tool to compare extractive (TF‑IDF) and abstractive (BART) methods and deploy a simple web interface.',
    features: [
      'Article fetching from Wikipedia API',
      'Extractive summarisation via TF‑IDF',
      'Abstractive summarisation using Hugging Face BART',
      'Side‑by‑side comparison UI',
      'Copy and download summaries'
    ],
    techStack: 'Python, Hugging Face Transformers, Flask, HTML/CSS, JavaScript',
    architecture: 'Flask backend → Wikipedia API for article text → Transformers pipeline for BART → TF‑IDF summariser via NLTK. Frontend vanilla JS fetches from Flask endpoints.',
    codeWalkthrough: [
      'The extractive summariser scores sentences based on TF‑IDF word frequencies and selects top‑k.',
      'The abstractive summariser uses `facebook/bart-large-cnn` via Hugging Face pipeline.',
      'Check `app.py` for the Flask routes and `summarizer.py` for the core logic.'
    ],
    howToUse: 'https://wiki-summarizer-flask.onrender.com (free tier, may take a moment to spin up)',
    results: 'BART summaries were preferred 4:1 over extractive in a small user study of 15 participants.',
    futurePlans: 'Add multi‑language support and a browser extension.'
  },
  'Twitter-Sentiment-Analyzer': {
    title: 'Twitter Sentiment Analyzer',
    subtitle: 'Real‑time sentiment analysis dashboard for Twitter trends and keyword tracking.',
    motivation: 'I wanted to understand public sentiment during live events (elections, product launches) without paying for expensive tools. This app streams tweets and visualises sentiment in real time.',
    features: [
      'Twitter API v2 streaming',
      'VADER sentiment analysis',
      'Live dashboard with D3.js',
      'Keyword/hashtag filter',
      'Historical sentiment graphs'
    ],
    techStack: 'Python, Tweepy, VADER, Flask, D3.js, Chart.js',
    architecture: 'Twitter streaming service → Flask backend → WebSocket → frontend D3.js dashboard. Sentiment scores calculated per tweet and aggregated.',
    codeWalkthrough: [
      'The stream listener uses Tweepy’s `StreamingClient` to filter tweets by keyword.',
      'VADER analyses each tweet, emitting a compound score via Socket.io.',
      'The frontend D3.js bubble chart updates every second.'
    ],
    howToUse: 'Local only (requires Twitter API bearer token). See README for setup.',
    results: 'Tracked sentiment for #EarthDay2025 and visualised a clear positive spike during the global live stream.',
    futurePlans: 'Add topic modelling (LDA), compare sentiment across regions, and deploy a public demo with curated streams.'
  }
};